### ISSUE TITLE
Edit-ui: KeyError when trying to hit "Done" after an edit

### ISSUE THREAD

**Issue by george08** [stamen/maptcha-v2#1]
http://yotb.studio.stamen.com/place-rough/map/dd7795b0-1ef3-11e2-901d-00259071d532

Here's the dump I saw after I hit Done:

KeyError
KeyError: 'aspect'

Traceback (most recent call last)
File "/home/migurski/venvs/yotb/lib/python2.7/site-packages/flask/app.py", line 1701, in **call**

<pre>return self.wsgi_app(environ, start_response)</pre>

File "/home/migurski/venvs/yotb/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app

<pre>response = self.make_response(self.handle_exception(e))</pre>

File "/home/migurski/venvs/yotb/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app

<pre>response = self.full_dispatch_request()</pre>

File "/home/migurski/venvs/yotb/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request

<pre>rv = self.handle_user_exception(e)</pre>

File "/home/migurski/venvs/yotb/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request

<pre>rv = self.dispatch_request()</pre>

File "/home/migurski/venvs/yotb/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request

<pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>

File "/var/www/com.stamen.studio/yearofthebay/show/recent/edit_ui/app.py", line 99, in place_rough_map

<pre>place_roughly(map_dom, roughplace_dom, queue, map, ul_lat, ul_lon, lr_lat, lr_lon)</pre>

File "/var/www/com.stamen.studio/yearofthebay/show/recent/edit_ui/data.py", line 197, in place_roughly

<pre>update_map_rough_consensus(map_dom, place_dom, map)</pre>

File "/var/www/com.stamen.studio/yearofthebay/show/recent/edit_ui/data.py", line 324, in update_map_rough_consensus

<pre>for p in placements]</pre>

KeyError: 'aspect'

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by george08** [comment]
Looks like Skip This Map button doesn't do anything too. (Should move to next map in Atlas, or, if at the end of the list of Atlases, go back to a "View" page where you get to a bounding box that contains all the maps in that Atlas.)
